<script>
  import { Grid, Column, Row, ClickableTile, Link, UnorderedList, ListItem } from "carbon-components-svelte";
</script>

<Grid padding>
  <Row>
    <Column>
      <h1>Ohnologs database</h1>
    </Column>
  </Row>

  <Row>
    <Column>
      <p>
        Welcome to the ohnologs database. You can download our ohnolog dataset or make use of the many filtering,
        search, and visualisation features that our site has to offer.
      </p>
    </Column>
  </Row>

  <Row>
    <Column>
      <h3>Features</h3>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>Download our data</h4>

      <p>
        If you want to download our entire dataset, click <Link>here</Link>. Alternatively, you can choose what data to
        download by browsing to one of the following pages:
      </p>

      <div class="list">
        <UnorderedList>
          <ListItem><Link href="/ohnologs/species">Species page</Link></ListItem>
          <ListItem><Link href="/ohnologs/gene">Gene page</Link></ListItem>
        </UnorderedList>
      </div>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>Search our data</h4>

      <p>
        If you already have some genes of interest and want to search our database with those in mind, you can do so by
        browsing to one of the following pages:
      </p>

      <div class="list">
        <UnorderedList>
          <ListItem><Link href="/ohnologs/select">Selection page</Link></ListItem>
          <ListItem><Link href="/ohnologs/blast">BLAST page</Link></ListItem>
        </UnorderedList>
      </div>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>Visualise our data</h4>

      <p>
        If you want to visualise the data that you have selected, be that single genes or entire genomes, you can
        generate figures in real time on the following pages:
      </p>

      <div class="list">
        <UnorderedList>
          <ListItem><Link href="/ohnologs/circos">Circos page</Link></ListItem>
          <ListItem><Link href="/ohnologs/dotplot">Dotplot page</Link></ListItem>
          <ListItem><Link href="/ohnologs/tree">Phylogeny page</Link></ListItem>
          <ListItem><Link href="/ohnologs/synteny">Microsynteny page</Link></ListItem>
        </UnorderedList>
      </div>
    </Column>
  </Row>

  <Row>
    <Column>
      <h3>Use cases</h3>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>I have a favourite gene</h4>

      <p>
        You can visit the <Link href="/ohnologs/blast">BLAST</Link> page to find homologs of your favourite gene that are
        present in our database. For each BLAST hit you can:
      </p>

      <div class="list">
        <UnorderedList>
          <ListItem>View the gene in an external database such as Ensembl</ListItem>
          <ListItem>Jump to any relevant plots that include the gene</ListItem>
          <ListItem>Add any of the hits to your selection</ListItem>
        </UnorderedList>
      </div>

      <p>
        Genes that are currently in your selection can be downloaded. They will also be displayed differently in any of
        the plots generated by our website.
      </p>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>I'm interested in a specific gene family</h4>

      <p>
        You can visit the <Link href="/ohnologs/blast">BLAST</Link> page to
      </p>
    </Column>
  </Row>

  <Row>
    <Column>
      <h4>I like pretty graphs</h4>

      <p>
        You can visit the <Link href="/ohnologs/blast">BLAST</Link> page to
      </p>
    </Column>
  </Row>
</Grid>

<style>
  h4 {
    padding-bottom: 0.4rem;
  }

  .list {
    padding-left: 1rem;
    padding-top: 0.4rem;
    padding-bottom: 0.6rem;
  }
</style>
